apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: registersp.funcionalcorp.net.br/cloud/terraform:v1
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: harbor