apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: ma31121990/nodeapp:v1
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: ma31121990